# Generated by Django 5.1 on 2026-04-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Emoji icon", max_length=10),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BasePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Ingot, MS Flat Base, Angle Base", max_length=150
                    ),
                ),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Special notes like 'Jointless pipe +500'"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "name"],
                "unique_together": {("name", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Main image for this product type (e.g., HR Coil, Angle, etc.)",
                        null=True,
                        upload_to="products/types/",
                    ),
                ),
                (
                    "thickness_range",
                    models.CharField(
                        blank=True, help_text="e.g. 5 - 65 mm", max_length=120
                    ),
                ),
                (
                    "width_range",
                    models.CharField(
                        blank=True, help_text="e.g. 25 - 500 mm", max_length=120
                    ),
                ),
                ("length_range", models.CharField(blank=True, max_length=120)),
                (
                    "size_info",
                    models.TextField(
                        blank=True,
                        help_text="Common sizes like 75x40, 100x50, 16mm etc.",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="e.g. IS2062, 304, E250", max_length=400
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_types",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "product_interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        help_text="Exact size from Excel: 25x5, 75*40LC, 19od x 03 Kg, 50mm",
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for this specific size/variant",
                        null=True,
                        upload_to="products/variants/",
                    ),
                ),
                (
                    "differential",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Differential from base rate",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "final_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final rate per ton",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight per piece in Kg (especially for pipes)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_base_rate",
                    models.BooleanField(
                        default=False, help_text="Marked as 'B' in Excel"
                    ),
                ),
                (
                    "has_range",
                    models.BooleanField(
                        default=False, help_text="Rate is a range like 9000TO9500"
                    ),
                ),
                (
                    "extra_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 500 Extra, Ask During Transaction, 9000-9500",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="main.baseprice",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="main.producttype",
                    ),
                ),
            ],
            options={
                "ordering": ["size_label"],
                "unique_together": {("product_type", "size_label")},
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("new_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="main.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
