# Generated by Django 6.0.2 on 2026-04-04 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, help_text="Emoji icon", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="grade",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="product",
            name="length_range",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_unit",
            field=models.CharField(default="per MT", max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="size_info",
            field=models.TextField(
                blank=True, help_text="Size options e.g. channel sizes"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="thickness_range",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="width_range",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
