# Generated by Django 6.0.2 on 2026-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image (JPEG/PNG, max 5 MB recommended)",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
